### ISSUE TITLE
Error while activating fondy-woocommerce-payment-gateway 2.4.3

### ISSUE THREAD

**Issue by garciaaa** [cloudipsp/wordpress#1]
I have this error message while trying to activate plugin (Платежный шлюз Fondy для WooCommerce.
Версия 2.4.3):
`Parse error: syntax error, unexpected '[' in /.../wp-content/plugins/fondy-woocommerce-payment-gateway/woocommerce-fondy.php on line 541`

WooCommerce 3.2.1
WordPress 4.8.6

**Comment by garciaaa** [comment]
Ok, it will work without error on PHP since 5.4

**Comment by has-well** [comment]
https://github.com/cloudipsp/wordpress/commit/eae597a1bffeae4643d10003df80d5d6a164be18
