### ISSUE TITLE
Ваш плагін Fondy для Woocommerce застарів

### ISSUE THREAD

**Issue by viterzbayraku** [cloudipsp/wordpress#32]
Добрий день, ваш плагін Fondy для Woocommerce застарів, не підтримується в PHP 8.0, не підтримує переадресацію клієнта на оновлену сторінку платежів Fondy і не підтримує оновлений дизайн вашої платіжної системи. Чи не могли б ви його оновити?

**Comment by Neries** [comment]
Доброго дня. Дякуємо за ваш коментар!
Ми оновили наш плагін до версії 3.0.0. У ньому є підтримка php8 і підтримка нашого чекаута 2.0.
