### ISSUE TITLE
Paid Membership Pro - add on "Subscription Delay" and your add on

### ISSUE THREAD

**Issue by Mit9l** [cloudipsp/wordpress#7]
Hello! I has on website "PaidMemberShipPro" and your add on. I want in my site add testing period for users and not get pay ment for this. For this I install PaidMemberShipPro add on "Subscription Delays" (https://www.paidmembershipspro.com/add-ons/subscription-delays/) , configure and nothing to happen, trial period was end, but the money was not debbited(

Tell me please, your add-on work with PaidMembershipPro add on ?

**Comment by has-well** [comment]
Hello, with this add-on, plugin not tested, to initialize recurring payments our plugin must save the card token after initial payment, you can try check log, for more info about what happened.
