### ISSUE TITLE
Subscription cancellation on merchant’s website doesn’t stop recurring charges - PMPro

### ISSUE THREAD

**Issue by karen-sarkisyan** [cloudipsp/wordpress#8]
I’m using Paid Memberships Pro plugin and testing recurring payments for memberships.
The integration works fine for the initial payment and subscription.

However, if a subscriber cancels subscription on his/her account page, it does not stop recurring charges.

As long as there’s no way for subscriber to unsubscribe on IPSP’s website either, it’s a problem.

**Comment by has-well** [comment]
Unfortunately, cancelling subscription is available only through the merchant portal, as soon as such an opportunity becomes available via API, it's will be implemented in the module.
